//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientProductWS.MusteriWSConsumer {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MusteriSonuc", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MusteriSonuc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MusteriIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SirketIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MusteriAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MusteriID {
            get {
                return this.MusteriIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MusteriIDField, value) != true)) {
                    this.MusteriIDField = value;
                    this.RaisePropertyChanged("MusteriID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SirketID {
            get {
                return this.SirketIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SirketIDField, value) != true)) {
                    this.SirketIDField = value;
                    this.RaisePropertyChanged("SirketID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MusteriAdi {
            get {
                return this.MusteriAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.MusteriAdiField, value) != true)) {
                    this.MusteriAdiField = value;
                    this.RaisePropertyChanged("MusteriAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Telefon {
            get {
                return this.TelefonField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonField, value) != true)) {
                    this.TelefonField = value;
                    this.RaisePropertyChanged("Telefon");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MusteriWSConsumer.CustomerWSSoap")]
    public interface CustomerWSSoap {
        
        // CODEGEN: Generating message contract since element name MusteriGetirResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MusteriGetir", ReplyAction="*")]
        ClientProductWS.MusteriWSConsumer.MusteriGetirResponse MusteriGetir(ClientProductWS.MusteriWSConsumer.MusteriGetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MusteriGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientProductWS.MusteriWSConsumer.MusteriGetirResponse> MusteriGetirAsync(ClientProductWS.MusteriWSConsumer.MusteriGetirRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MusteriGetirRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MusteriGetir", Namespace="http://tempuri.org/", Order=0)]
        public ClientProductWS.MusteriWSConsumer.MusteriGetirRequestBody Body;
        
        public MusteriGetirRequest() {
        }
        
        public MusteriGetirRequest(ClientProductWS.MusteriWSConsumer.MusteriGetirRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class MusteriGetirRequestBody {
        
        public MusteriGetirRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MusteriGetirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MusteriGetirResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientProductWS.MusteriWSConsumer.MusteriGetirResponseBody Body;
        
        public MusteriGetirResponse() {
        }
        
        public MusteriGetirResponse(ClientProductWS.MusteriWSConsumer.MusteriGetirResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MusteriGetirResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientProductWS.MusteriWSConsumer.MusteriSonuc[] MusteriGetirResult;
        
        public MusteriGetirResponseBody() {
        }
        
        public MusteriGetirResponseBody(ClientProductWS.MusteriWSConsumer.MusteriSonuc[] MusteriGetirResult) {
            this.MusteriGetirResult = MusteriGetirResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CustomerWSSoapChannel : ClientProductWS.MusteriWSConsumer.CustomerWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerWSSoapClient : System.ServiceModel.ClientBase<ClientProductWS.MusteriWSConsumer.CustomerWSSoap>, ClientProductWS.MusteriWSConsumer.CustomerWSSoap {
        
        public CustomerWSSoapClient() {
        }
        
        public CustomerWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientProductWS.MusteriWSConsumer.MusteriGetirResponse ClientProductWS.MusteriWSConsumer.CustomerWSSoap.MusteriGetir(ClientProductWS.MusteriWSConsumer.MusteriGetirRequest request) {
            return base.Channel.MusteriGetir(request);
        }
        
        public ClientProductWS.MusteriWSConsumer.MusteriSonuc[] MusteriGetir() {
            ClientProductWS.MusteriWSConsumer.MusteriGetirRequest inValue = new ClientProductWS.MusteriWSConsumer.MusteriGetirRequest();
            inValue.Body = new ClientProductWS.MusteriWSConsumer.MusteriGetirRequestBody();
            ClientProductWS.MusteriWSConsumer.MusteriGetirResponse retVal = ((ClientProductWS.MusteriWSConsumer.CustomerWSSoap)(this)).MusteriGetir(inValue);
            return retVal.Body.MusteriGetirResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientProductWS.MusteriWSConsumer.MusteriGetirResponse> ClientProductWS.MusteriWSConsumer.CustomerWSSoap.MusteriGetirAsync(ClientProductWS.MusteriWSConsumer.MusteriGetirRequest request) {
            return base.Channel.MusteriGetirAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientProductWS.MusteriWSConsumer.MusteriGetirResponse> MusteriGetirAsync() {
            ClientProductWS.MusteriWSConsumer.MusteriGetirRequest inValue = new ClientProductWS.MusteriWSConsumer.MusteriGetirRequest();
            inValue.Body = new ClientProductWS.MusteriWSConsumer.MusteriGetirRequestBody();
            return ((ClientProductWS.MusteriWSConsumer.CustomerWSSoap)(this)).MusteriGetirAsync(inValue);
        }
    }
}
