//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientProductWS.ProductWSConsumer {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UrunSonuc", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UrunSonuc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int UrunIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrunAdiField;
        
        private System.Nullable<decimal> FiyatField;
        
        private System.Nullable<short> StokField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int UrunID {
            get {
                return this.UrunIDField;
            }
            set {
                if ((this.UrunIDField.Equals(value) != true)) {
                    this.UrunIDField = value;
                    this.RaisePropertyChanged("UrunID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UrunAdi {
            get {
                return this.UrunAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.UrunAdiField, value) != true)) {
                    this.UrunAdiField = value;
                    this.RaisePropertyChanged("UrunAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<decimal> Fiyat {
            get {
                return this.FiyatField;
            }
            set {
                if ((this.FiyatField.Equals(value) != true)) {
                    this.FiyatField = value;
                    this.RaisePropertyChanged("Fiyat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<short> Stok {
            get {
                return this.StokField;
            }
            set {
                if ((this.StokField.Equals(value) != true)) {
                    this.StokField = value;
                    this.RaisePropertyChanged("Stok");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductWSConsumer.ProductWsSoap")]
    public interface ProductWsSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ClientProductWS.ProductWSConsumer.HelloWorldResponse HelloWorld(ClientProductWS.ProductWSConsumer.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientProductWS.ProductWSConsumer.HelloWorldResponse> HelloWorldAsync(ClientProductWS.ProductWSConsumer.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name UrunleriGetirResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UrunleriGetir", ReplyAction="*")]
        ClientProductWS.ProductWSConsumer.UrunleriGetirResponse UrunleriGetir(ClientProductWS.ProductWSConsumer.UrunleriGetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UrunleriGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientProductWS.ProductWSConsumer.UrunleriGetirResponse> UrunleriGetirAsync(ClientProductWS.ProductWSConsumer.UrunleriGetirRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ClientProductWS.ProductWSConsumer.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ClientProductWS.ProductWSConsumer.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientProductWS.ProductWSConsumer.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ClientProductWS.ProductWSConsumer.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UrunleriGetirRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UrunleriGetir", Namespace="http://tempuri.org/", Order=0)]
        public ClientProductWS.ProductWSConsumer.UrunleriGetirRequestBody Body;
        
        public UrunleriGetirRequest() {
        }
        
        public UrunleriGetirRequest(ClientProductWS.ProductWSConsumer.UrunleriGetirRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UrunleriGetirRequestBody {
        
        public UrunleriGetirRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UrunleriGetirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UrunleriGetirResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientProductWS.ProductWSConsumer.UrunleriGetirResponseBody Body;
        
        public UrunleriGetirResponse() {
        }
        
        public UrunleriGetirResponse(ClientProductWS.ProductWSConsumer.UrunleriGetirResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UrunleriGetirResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ClientProductWS.ProductWSConsumer.UrunSonuc> UrunleriGetirResult;
        
        public UrunleriGetirResponseBody() {
        }
        
        public UrunleriGetirResponseBody(System.Collections.Generic.List<ClientProductWS.ProductWSConsumer.UrunSonuc> UrunleriGetirResult) {
            this.UrunleriGetirResult = UrunleriGetirResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductWsSoapChannel : ClientProductWS.ProductWSConsumer.ProductWsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductWsSoapClient : System.ServiceModel.ClientBase<ClientProductWS.ProductWSConsumer.ProductWsSoap>, ClientProductWS.ProductWSConsumer.ProductWsSoap {
        
        public ProductWsSoapClient() {
        }
        
        public ProductWsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductWsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductWsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductWsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientProductWS.ProductWSConsumer.HelloWorldResponse ClientProductWS.ProductWSConsumer.ProductWsSoap.HelloWorld(ClientProductWS.ProductWSConsumer.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ClientProductWS.ProductWSConsumer.HelloWorldRequest inValue = new ClientProductWS.ProductWSConsumer.HelloWorldRequest();
            inValue.Body = new ClientProductWS.ProductWSConsumer.HelloWorldRequestBody();
            ClientProductWS.ProductWSConsumer.HelloWorldResponse retVal = ((ClientProductWS.ProductWSConsumer.ProductWsSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientProductWS.ProductWSConsumer.HelloWorldResponse> ClientProductWS.ProductWSConsumer.ProductWsSoap.HelloWorldAsync(ClientProductWS.ProductWSConsumer.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientProductWS.ProductWSConsumer.HelloWorldResponse> HelloWorldAsync() {
            ClientProductWS.ProductWSConsumer.HelloWorldRequest inValue = new ClientProductWS.ProductWSConsumer.HelloWorldRequest();
            inValue.Body = new ClientProductWS.ProductWSConsumer.HelloWorldRequestBody();
            return ((ClientProductWS.ProductWSConsumer.ProductWsSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientProductWS.ProductWSConsumer.UrunleriGetirResponse ClientProductWS.ProductWSConsumer.ProductWsSoap.UrunleriGetir(ClientProductWS.ProductWSConsumer.UrunleriGetirRequest request) {
            return base.Channel.UrunleriGetir(request);
        }
        
        public System.Collections.Generic.List<ClientProductWS.ProductWSConsumer.UrunSonuc> UrunleriGetir() {
            ClientProductWS.ProductWSConsumer.UrunleriGetirRequest inValue = new ClientProductWS.ProductWSConsumer.UrunleriGetirRequest();
            inValue.Body = new ClientProductWS.ProductWSConsumer.UrunleriGetirRequestBody();
            ClientProductWS.ProductWSConsumer.UrunleriGetirResponse retVal = ((ClientProductWS.ProductWSConsumer.ProductWsSoap)(this)).UrunleriGetir(inValue);
            return retVal.Body.UrunleriGetirResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientProductWS.ProductWSConsumer.UrunleriGetirResponse> ClientProductWS.ProductWSConsumer.ProductWsSoap.UrunleriGetirAsync(ClientProductWS.ProductWSConsumer.UrunleriGetirRequest request) {
            return base.Channel.UrunleriGetirAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientProductWS.ProductWSConsumer.UrunleriGetirResponse> UrunleriGetirAsync() {
            ClientProductWS.ProductWSConsumer.UrunleriGetirRequest inValue = new ClientProductWS.ProductWSConsumer.UrunleriGetirRequest();
            inValue.Body = new ClientProductWS.ProductWSConsumer.UrunleriGetirRequestBody();
            return ((ClientProductWS.ProductWSConsumer.ProductWsSoap)(this)).UrunleriGetirAsync(inValue);
        }
    }
}
